name: PR-check
on: 
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
      - 'labeled'
  pull_request_target:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
      - 'labeled'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  add-summary-comment:
    runs-on: ubuntu-latest
    steps:
    - name: add PR comment
      if: always() && github.event_name == 'pull_request_target'
      uses: actions/github-script@v6
      with:
        script: |
          let fs = require('fs');
          var summary = await fs.readFile(process.env.GITHUB_STEP_SUMMARY);
          summary += " HELLO WORLD";
          console.log('summary', summary);
          
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: summary
          });
